### ISSUE TITLE
app-shells/gitstatus-1.5.3 failed to install

### ISSUE THREAD

**Issue by geekshen8521** [Gentoo-zh/gentoo-zh#1491]
```
>>> Install app-shells/gitstatus-1.5.3 into /var/tmp/portage/app-shells/gitstatus-1.5.3/image
Traceback (most recent call last):
  File "/usr/lib/portage/python3.9/doins.py", line 607, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.9/doins.py", line 596, in main
    if _doins(
  File "/usr/lib/portage/python3.9/doins.py", line 439, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.9/doins.py", line 373, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.9/doins.py", line 181, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'gitstatus.*.zsh.zwc'
 * ERROR: app-shells/gitstatus-1.5.3::gentoo-zh failed (install phase):
 *   doins failed
 *
```

**Comment by geekshen8521** [comment]
USE="-zsh-completion"
I think it fails at this line 
https://github.com/microcai/gentoo-zh/blob/93936419e8dd43008622f7306d8500c913222fae/app-shells/gitstatus/gitstatus-1.5.3.ebuild#L85

It seems that there is no file with suffix `zwc` upstream with `v1.5.3`

**Comment by aieu** [comment]
ping @OriPoin
