### ISSUE TITLE
conda-libmamba-solver-24.1.0 has missing dependency

### ISSUE THREAD

**Issue by bogpetre** [Gentoo-zh/gentoo-zh#4373]
conda-libmamba-solver fails to build with the following error,

```
python3.11 -m gpep517 build-wheel --prefix=/usr --backend hatchling.build --output-fd 3 --wheel-dir /var/tmp/portage/dev-python/conda-libmamba-solver-24.1.0/work/conda-libmamba-solver-24.1.0_python3.11/wheel
2024-03-12 18:08:17,979 gpep517 INFO Building wheel via backend hatchling.build
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1421, in cached
    self._cached = self.source.get_version_data()['version']
                   ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1471, in source
    raise UnknownPluginError(message)
hatchling.plugin.exceptions.UnknownPluginError: Unknown version source: vcs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 429, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 425, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 215, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpep517/__main__.py", line 207, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
    _ = self.version
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 128, in version
    self._version = self._get_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 226, in _get_version
    version = self.hatch.version.cached
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1423, in cached
    message = f'Error getting the version from source `{self.source.PLUGIN_NAME}`: {e}'
                                                        ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/hatchling/metadata/core.py", line 1471, in source
    raise UnknownPluginError(message)
hatchling.plugin.exceptions.UnknownPluginError: Unknown version source: vcs

```

The problem is a missing dev-python/hatch-vcs dependency. It's similar to a problem previously reported here:

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4b1e89d591825480acaf2e11aa58076b963d69c4

The following patch to the ebuild resolves the issue, also implemented in a fork and proposed as a change here [a6c7115](https://github.com/microcai/gentoo-zh/commit/a6c711579bc1437c807928ee15a46723dbec4fc8).

```
--- a/dev-python/conda-libmamba-solver/conda-libmamba-solver-24.1.0.ebuild_bak	2024-03-12 18:18:42.965240421 -0400
+++ b/dev-python/conda-libmamba-solver/conda-libmamba-solver-24.1.0.ebuild	2024-03-12 18:14:31.004745831 -0400
@@ -18,7 +18,8 @@
 
 S="${WORKDIR}/conda-libmamba-solver-${PV}"
 
-BDEPEND="$(python_gen_cond_dep 'dev-python/setuptools-scm[${PYTHON_USEDEP}]')"
+BDEPEND="$(python_gen_cond_dep 'dev-python/setuptools-scm[${PYTHON_USEDEP}]')
+        $(python_gen_cond_dep 'dev-python/hatch-vcs[${PYTHON_USEDEP}]')"
 
 RDEPEND="
 	$(python_gen_cond_dep 'dev-python/boltons[${PYTHON_USEDEP}]')

```

**Comment by liangyongxiang** [comment]
@OriPoin
